CREATE TABLE MEMBER (
    MEMBER_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    LOGIN_ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    UUID VARCHAR(255),
    BALANCE BIGINT DEFAULT 0 NOT NULL
);

CREATE TABLE ITEM (
    ITEM_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ITEM_NAME VARCHAR(255) NOT NULL,
    PRICE INT NOT NULL,
    QUANTITY INT NOT NULL,
    MEMBER_ID BIGINT NOT NULL
    CONSTRAINT FK_ITEM_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID)
);

CREATE TABLE CART (
    CART_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    MEMBER_ID BIGINT NOT NULL,
    ITEM_ID BIGINT NOT NULL,
    QUANTITY BIGINT NOT NULL DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CART_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    CONSTRAINT FK_CART_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ITEM_ID)
);

CREATE TABLE PURCHASE (
    PURCHASE_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    MEMBER_ID BIGINT NOT NULL,
    ITEM_ID BIGINT NOT NULL,
    QUANTITY BIGINT NOT NULL DEFAULT 1,
    TOTAL_PRICE BIGINT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PURCHASE_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    CONSTRAINT FK_PURCHASE_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEM (ITEM_ID)
);

ALTER TABLE MEMBER ADD CONSTRAINT UQ_MEMBER_LOGIN_ID UNIQUE (LOGIN_ID);
