CREATE TABLE MEMBER (
    MEMBER_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    LOGIN_ID VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    UUID VARCHAR(255),
    BALANCE DOUBLE PRECISION DEFAULT 0.0 NOT NULL
);

CREATE TABLE ITEM (
    ITEM_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    ITEM_NAME VARCHAR(255) NOT NULL,
    PRICE INT NOT NULL,
    QUANTITY INT NOT NULL,
    MEMBER_ID BIGINT NOT NULL
);

ALTER TABLE MEMBER ADD CONSTRAINT UQ_MEMBER_LOGIN_ID UNIQUE (LOGIN_ID);

ALTER TABLE ITEM ADD CONSTRAINT FK_ITEM_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID) NOCHECK;
